<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="FirebaseAuthentication.net" Version="4.1.0" />
    <PackageReference Include="FirebaseDatabase.net" Version="5.0.0" />
    <PackageReference Include="Supabase" Version="1.1.1" />
    <PackageReference Include="Supabase.Gotrue" Version="6.0.3" />
  </ItemGroup>


	</Project>
